services:
  app:
    image: ghcr.io/vmtech-services/rat_catcher_bot:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/bot/data
