services:
  bot:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    image: rat-bot:latest
    container_name: rat-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
