services:
  bot:
    build: .
    image: rat-bot:latest
    container_name: rat-bot
    restart: always
    args:
      DATABASE_URL: ${DATABASE_URL}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
