name: rat-today deploy

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & deploy with docker-compose
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Stop and remove existing containers
        shell: powershell
        run: |
          docker compose down --remove-orphans

      - name: Write environment variables to .env file
        shell: powershell
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" | Out-File -FilePath .env -Encoding ascii
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" | Out-File -FilePath .env -Encoding ascii -Append

      - name: Build and start new container
        shell: powershell
        run: |
          docker compose up -d --build
